### ISSUE TITLE
Add `-h` as alias for `--help`

### ISSUE THREAD

**Issue by mattkram** [travishathaway/conda-envlock#3]
I noticed the plugin raises an exception when I tried `conda protect -h`. Since `conda` accepts `-h`, this was a little confusing.

Also, since the exception was unhandled, it triggered the generic "There is an error in a plugin" message from `conda`, which is very verbose.

```
❯ conda protect -h

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/mattkram/miniconda3/lib/python3.10/site-packages/click/parser.py", line 514, in _process_opts
        self._match_long_opt(norm_long_opt, explicit_value, state)
      File "/Users/mattkram/miniconda3/lib/python3.10/site-packages/click/parser.py", line 398, in _match_long_opt
        raise NoSuchOption(opt, possibilities=possibilities, ctx=self.ctx)
    click.exceptions.NoSuchOption: No such option: -h

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/mattkram/miniconda3/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "/Users/mattkram/miniconda3/lib/python3.10/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
      File "/Users/mattkram/miniconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 175, in do_call
        result = plugin_subcommand.action(getattr(args, "_args", args))
      File "/Users/mattkram/miniconda3/lib/python3.10/site-packages/conda_protect/main.py", line 226, in guard_wrapper
        guard(args=args, prog_name=f"conda {GUARD_COMMAND_NAME}", standalone_mode=False)
      File "/Users/mattkram/miniconda3/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
        return self.main(*args, **kwargs)
      File "/Users/mattkram/miniconda3/lib/python3.10/site-packages/click/core.py", line 1077, in main
        with self.make_context(prog_name, args, **extra) as ctx:
      File "/Users/mattkram/miniconda3/lib/python3.10/site-packages/click/core.py", line 943, in make_context
        self.parse_args(ctx, args)
      File "/Users/mattkram/miniconda3/lib/python3.10/site-packages/click/core.py", line 1405, in parse_args
        opts, args, param_order = parser.parse_args(args=args)
      File "/Users/mattkram/miniconda3/lib/python3.10/site-packages/click/parser.py", line 337, in parse_args
        self._process_args_for_options(state)
      File "/Users/mattkram/miniconda3/lib/python3.10/site-packages/click/parser.py", line 364, in _process_args_for_options
        self._process_opts(arg, state)
      File "/Users/mattkram/miniconda3/lib/python3.10/site-packages/click/parser.py", line 523, in _process_opts
        self._match_short_opt(arg, state)
      File "/Users/mattkram/miniconda3/lib/python3.10/site-packages/click/parser.py", line 436, in _match_short_opt
        raise NoSuchOption(opt, ctx=self.ctx)
    click.exceptions.NoSuchOption: No such option: -h

`$ /Users/mattkram/miniconda3/bin/conda protect -h`

 <REDACTED>

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

Upload successful.
```

**Comment by travishathaway** [comment]
@mattkram,

Thanks for reporting this. I think this is actually a pretty easy fix. It just requires configuring `click` to recognize the `-h` option for outputting the help dialog.

We could add it as a milestone for the next release.
